services:
  message-handler:
    user: root
    container_name: message-handler
    ports:
      - 8080:8080
    expose:
      - 9092
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    depends_on:
      - kafka-1
    networks:
      - message-network

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - message-network

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9095:9094"
    expose:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data/500:/kafka
    depends_on:
      - zookeeper
    networks:
      - message-network

networks:
  message-network:
    driver: bridge
